### ISSUE TITLE
Device discovery isn't working?

### ISSUE THREAD

**Issue by JwJason** [sandeepmistry/node-lumen#4]
I have a Lumen 8 Wifi enabled smart bulb on my network, and my iOS app picks it up just fine. However, test.js isn't picking up anything. Have you tried this lately?

**Comment by sandeepmistry** [comment]
@JwJason this library only supports Lumen Bluetooth Low Energy bulbs. I've update the read me accordingly in https://github.com/sandeepmistry/node-lumen/commit/4d1afd4319e3a5ba895988889293128501cbfffd.
